### ISSUE TITLE
Improve the readme file

### ISSUE THREAD

**Issue by annu12340** [annu12340/Dapp-voting-system#4]
Update the readme file with:-

Better description in the readme
Installation steps

Take these repos as example
https://github.com/annu12340/virtual-white-board
https://github.com/annu12340/Choose-Smart

**Comment by beckettnormington** [comment]
Hi, could you assign me this? I'll try and get it done by today or tomorrow.

**Comment by annu12340** [comment]
Go ahead @beckettnormington

**Comment by beckettnormington** [comment]
@annu12340, my Node installation got destroyed by my antivirus (McAfee), so I can't use the program. I still plan on adding a section on **why** blockchain is secure / a basic explanation of the concept. Again, apologies for the mishap. 😞

**Comment by beckettnormington** [comment]
@annu12340, I edited the README to the best of my ability. I couldn't add the installation section, but I did add a specific section on blockchain. PR #5

**Comment by FarhanMuftiHilmy** [comment]
Could you assign me too, please?

**Comment by annu12340** [comment]
Solved
